name: Run security scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  semgrep-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ">=1.24"

      - name: Install Semgrep
        run: |
          go mod download
          go test
